### ISSUE TITLE
Receipt should be sent by email after payment

### ISSUE THREAD

**Issue by knicklabs** [CoworkingNiagara/joindot#4]
A receipt should be emailed to the user after they complete the payment step. I received a welcome email (which was great) but no receipt confirming the amount paid and date.

**Comment by adam12** [comment]
Thanks for reporting this. :+1: 

When I tested in live, I could of swore I received one, but reading over Stripe docs, I'd have to create a user or pass in a flag to send the receipt email, which I am not currently doing.
